export const mockDataSets = {
  financial: [
    {
      quarter: "Q1 2025",
      revenue: "$1,245,000",
      expenses: "$980,000",
      profit: "$265,000",
      growth: "12%",
    },
    {
      quarter: "Q2 2025",
      revenue: "$1,380,000",
      expenses: "$1,050,000",
      profit: "$330,000",
      growth: "15%",
    },
    {
      quarter: "Q3 2025",
      revenue: "$1,520,000",
      expenses: "$1,120,000",
      profit: "$400,000",
      growth: "18%",
    },
    {
      quarter: "Q4 2025",
      revenue: "$1,680,000",
      expenses: "$1,210,000",
      profit: "$470,000",
      growth: "21%",
    },
    {
      quarter: "Q1 2026",
      revenue: "$1,750,000",
      expenses: "$1,280,000",
      profit: "$470,000",
      growth: "4%",
    },
    {
      quarter: "Q2 2026",
      revenue: "$1,830,000",
      expenses: "$1,320,000",
      profit: "$510,000",
      growth: "5%",
    },
  ],
  market: [
    {
      product: "Product A",
      market_share: "25%",
      competitors: "4",
      growth_rate: "8%",
      region: "North America",
    },
    {
      product: "Product B",
      market_share: "20%",
      competitors: "3",
      growth_rate: "5%",
      region: "Europe",
    },
    {
      product: "Product C",
      market_share: "30%",
      competitors: "2",
      growth_rate: "12%",
      region: "Asia",
    },
    {
      product: "Product D",
      market_share: "15%",
      competitors: "5",
      growth_rate: "3%",
      region: "South America",
    },
    {
      product: "Product E",
      market_share: "10%",
      competitors: "6",
      growth_rate: "2%",
      region: "Africa",
    },
  ],
  performance: [
    {
      metric: "Response Time",
      current: "120ms",
      previous: "180ms",
      improvement: "33%",
      industry_avg: "150ms",
    },
    {
      metric: "Uptime",
      current: "99.95%",
      previous: "99.8%",
      improvement: "0.15%",
      industry_avg: "99.5%",
    },
    {
      metric: "User Engagement",
      current: "8.5 min",
      previous: "7.2 min",
      improvement: "18%",
      industry_avg: "6.8 min",
    },
    {
      metric: "Conversion Rate",
      current: "3.8%",
      previous: "3.2%",
      improvement: "19%",
      industry_avg: "2.9%",
    },
    {
      metric: "Error Rate",
      current: "0.12%",
      previous: "0.25%",
      improvement: "52%",
      industry_avg: "0.3%",
    },
  ],
  demographic: [
    {
      age_group: "18-24",
      percentage: "15%",
      growth: "5%",
      location: "Urban",
      income: "$30K-$50K",
    },
    {
      age_group: "25-34",
      percentage: "30%",
      growth: "8%",
      location: "Urban",
      income: "$50K-$80K",
    },
    {
      age_group: "35-44",
      percentage: "25%",
      growth: "3%",
      location: "Suburban",
      income: "$80K-$120K",
    },
    {
      age_group: "45-54",
      percentage: "20%",
      growth: "1%",
      location: "Suburban",
      income: "$100K-$150K",
    },
    {
      age_group: "55+",
      percentage: "10%",
      growth: "-2%",
      location: "Rural",
      income: "$70K-$100K",
    },
  ],
}

// Keep the original mockScrapeData for backward compatibility
export const mockScrapeData = {
  jobs: [
    {
      title: "Software Engineer",
      company: "Tech Corp",
      location: "San Francisco, CA",
      salary: "$150,000",
      description: "Develop and maintain web applications.",
    },
    {
      title: "Data Scientist",
      company: "Data Solutions Inc.",
      location: "New York, NY",
      salary: "$160,000",
      description: "Analyze large datasets and build machine learning models.",
    },
    {
      title: "Product Manager",
      company: "Innovate Ltd.",
      location: "Seattle, WA",
      salary: "$140,000",
      description: "Define and execute product strategy.",
    },
  ],
  prices: [
    {
      product: "Laptop",
      price: "$1200",
      store: "Best Buy",
      availability: "In Stock",
    },
    {
      product: "Smartphone",
      price: "$800",
      store: "Amazon",
      availability: "Out of Stock",
    },
    {
      product: "Tablet",
      price: "$300",
      store: "Walmart",
      availability: "In Stock",
    },
  ],
  news: [
    {
      title: "Stock Market Soars",
      source: "Reuters",
      date: "2024-01-01",
      summary: "The stock market reached a new high.",
    },
    {
      title: "Interest Rates Rise",
      source: "Bloomberg",
      date: "2024-01-02",
      summary: "The Federal Reserve raised interest rates.",
    },
    {
      title: "Inflation Remains High",
      source: "CNN",
      date: "2024-01-03",
      summary: "Inflation continues to be a concern.",
    },
  ],
  real_estate: [
    {
      address: "123 Main St",
      city: "Los Angeles, CA",
      price: "$1,000,000",
      bedrooms: "3",
      bathrooms: "2",
    },
    {
      address: "456 Oak Ave",
      city: "Chicago, IL",
      price: "$500,000",
      bedrooms: "2",
      bathrooms: "1",
    },
    {
      address: "789 Pine Ln",
      city: "Houston, TX",
      price: "$300,000",
      bedrooms: "4",
      bathrooms: "3",
    },
  ],
}
